### ISSUE TITLE
/.config/vbox/vboxvms.conf not found

### ISSUE THREAD

**Issue by waz452** [alst-ovh/mac_vboxautostart#2]
Everything seems to install perfectly ... there's no error messages.  
However when I try to vbox.sh cfg, thats when the error msgs begin.

———

wazza /Users/wazza/mac_vboxautostart
→ ./install.sh
Password:
/usr/local/bin/shutdown.sh -> /Users/wazza/Library/VBox/shutdown.sh
/usr/local/bin/vbox.sh -> /Users/wazza/Library/VBox/vbox.sh
/usr/local/bin/vboxvmscfg.sh -> /Users/wazza/Library/VBox/vboxvmscfg.sh
chmod: /Users/wazza/Library/Application Support/com.pkamb.PowerKey/shutdownPowerKey.sh: Not a directory

wazza /Users/wazza/mac_vboxautostart
→

———

wazza /Users/wazza/mac_vboxautostart
→ vbox.sh cfg
 ==> /Users/wazza/.config/vbox/vboxvms.conf not found ...
  ==> Create /Users/wazza/.config/vbox/vboxvms.conf, please wait ...
/usr/local/bin/vbox.sh: line 93: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 95: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 95: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 95: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 95: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 95: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 57: /Users/wazza/.config/vbox/vboxvms.conf: No such file or directory
/usr/local/bin/vbox.sh: line 127: /Users/wazza/.config/vbox/vboxvms.conf: No such file or directory
rm: /Users/wazza/.config/vbox/vboxvms.conf1: No such file or directory
/usr/local/bin/vbox.sh: line 85: /Users/wazza/.config/vbox/vboxvms.conf: No such file or directory
Activate VMs Config now ? [y/n]
n

wazza /Users/wazza/mac_vboxautostart
→

**Comment by alst-ovh** [comment]
Install first a VM in Virtualbox.
